sudo: true

language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository

before_script:
  - export SKIP_OKBUCK=true
  - mkdir -p $ANDROID_HOME/licenses
  - echo $android_sdk_license > $ANDROID_HOME/licenses/android-sdk-license
  - echo $android_sdk_preview_license > $ANDROID_HOME/licenses/android-sdk-preview-license
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &

# safelist
branches:
  only:
  - master

notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - buck-out/cache
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/